server:
  port: 8110
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-gateway
  cloud:
    gateway:
  #可以根据请求参数,cookie,host,请求时间,请求头等进行校验判断路由, 下面根据先后顺序转发
      routes:
        - id: baidu_route
          uri: http://www.baidu.com:80
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1
      enabled: true

#
#eureka:
#  client:
#    service-url:
#      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
#    prefer-ip-address: true
